[2024/05/21|09:38:26][INFO]:擴充指令初始化完成
[2024/05/21|09:38:26][INFO]:logging in using static token
[2024/05/21|09:38:28][INFO]:Shard ID None has connected to Gateway (Session ID: 4d7d4f7203331319ac2a55678b9dc5c5).
[2024/05/21|09:38:31][INFO]:已載入18個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|09:38:31][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|09:39:45][ERROR]:Ignoring exception in command tree
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1089, in wrapper
    await self._call(interaction)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1221, in _call
    command, options = self._get_app_command_options(data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1125, in _get_app_command_options
    raise CommandNotFound(name, parents)
discord.app_commands.errors.CommandNotFound: Application command 'add' not found
[2024/05/21|09:40:39][INFO]:更新 profileOnline 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|09:40:39][INFO]:更新 profileStar 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|09:40:39][INFO]:lightinvi<428845649279188992> 加入 光隱測試區<1029978425550704640> 的語音頻道
[2024/05/21|09:40:39][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 請加入任意語音頻道
[2024/05/21|09:40:47][ERROR]:Ignoring exception in command 'skip'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 82, in skip_music
    await interaction.response.send_message("正在跳過當前音樂")
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\interactions.py", line 774, in send_message
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'skip' raised an exception: InteractionResponded: This interaction has already been responded to before
[2024/05/21|09:41:06][INFO]:Connecting to voice...
[2024/05/21|09:41:06][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|09:41:07][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|09:41:09][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|09:41:10][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|09:41:19][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 指令處理中
[2024/05/21|09:41:20][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 正在播放善宇 - 做自己的光，不需要太亮「人們只看結果不看過程 喜歡用分數決定人生」【動態歌詞/PinyinLyrics】♪
[2024/05/21|09:41:51][INFO]:Connecting to voice...
[2024/05/21|09:41:51][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|09:41:52][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|09:41:54][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|09:41:54][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|09:42:04][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 指令處理中
[2024/05/21|09:42:04][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 正在播放5566 我難過 歌詞
[2024/05/21|09:45:30][INFO]:擴充指令初始化完成
[2024/05/21|09:45:30][INFO]:logging in using static token
[2024/05/21|09:45:31][INFO]:Shard ID None has connected to Gateway (Session ID: 3847e43f873b5876e18f5b7d3ecb2e86).
[2024/05/21|09:45:34][INFO]:已載入18個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|09:45:34][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|09:45:59][INFO]:Connecting to voice...
[2024/05/21|09:45:59][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|09:46:00][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|09:46:02][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 37, in play_music
    await interactions.response.send_message("指令處理中",delete_after=10)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\webhook\async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
[2024/05/21|09:46:56][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|09:46:56][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|09:46:59][INFO]:擴充指令初始化完成
[2024/05/21|09:46:59][INFO]:logging in using static token
[2024/05/21|09:47:00][INFO]:Shard ID None has connected to Gateway (Session ID: 7b1b386cece4c968b500c032ddeae155).
[2024/05/21|09:47:03][INFO]:已載入18個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|09:47:03][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|09:47:41][INFO]:Connecting to voice...
[2024/05/21|09:47:41][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|09:47:42][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|09:47:54][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 指令處理中
[2024/05/21|09:48:03][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 正在播放善宇 - 做自己的光，不需要太亮「人們只看結果不看過程 喜歡用分數決定人生」【動態歌詞/PinyinLyrics】♪
[2024/05/21|09:50:25][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|09:50:25][INFO]:ffmpeg process 6512 successfully terminated with return code of 0.
[2024/05/21|09:50:25][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|09:50:36][INFO]:擴充指令初始化完成
[2024/05/21|09:50:36][INFO]:logging in using static token
[2024/05/21|09:50:38][INFO]:Shard ID None has connected to Gateway (Session ID: 5462b9becad8be8347dcda27e4c0acd9).
[2024/05/21|09:50:40][INFO]:已載入18個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|09:50:40][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|09:51:12][INFO]:Connecting to voice...
[2024/05/21|09:51:12][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|09:51:12][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|09:51:26][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 指令處理中
[2024/05/21|09:51:29][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 正在播放善宇 - 做自己的光，不需要太亮「人們只看結果不看過程 喜歡用分數決定人生」【動態歌詞/PinyinLyrics】♪
[2024/05/21|09:51:41][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|09:51:41][INFO]:ffmpeg process 6420 has not terminated. Waiting to terminate...
[2024/05/21|09:51:41][INFO]:ffmpeg process 6420 should have terminated with a return code of 1.
[2024/05/21|09:51:41][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|10:31:28][INFO]:擴充指令初始化完成
[2024/05/21|10:31:28][INFO]:logging in using static token
[2024/05/21|10:31:29][INFO]:Shard ID None has connected to Gateway (Session ID: 995c7f004c1ad213d79341d7a8ad81f9).
[2024/05/21|10:31:32][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|10:31:32][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|10:32:19][INFO]:Connecting to voice...
[2024/05/21|10:32:19][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|10:32:20][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|10:32:33][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 指令處理中
[2024/05/21|10:32:36][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 正在播放爱情转移 陈奕迅 (歌词版)
[2024/05/21|10:33:21][WARNING]:lightinvi<428845649279188992> 異常上線時間紀錄
[2024/05/21|10:33:30][INFO]:更新 profileOnline 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|10:33:30][INFO]:更新 profileStar 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|10:33:30][INFO]:lightinvi<428845649279188992> 加入 光隱測試區<1029978425550704640> 的語音頻道
[2024/05/21|10:33:46][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 已暫停當前音樂
[2024/05/21|10:34:01][ERROR]:Ignoring exception in command 'resume'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 112, in resume_music
    await self.music_console.resume
TypeError: object method can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'resume' raised an exception: TypeError: object method can't be used in 'await' expression
[2024/05/21|10:34:11][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 已恢復音樂撥放
[2024/05/21|10:34:56][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|10:34:56][INFO]:ffmpeg process 712 has not terminated. Waiting to terminate...
[2024/05/21|10:34:56][INFO]:ffmpeg process 712 should have terminated with a return code of 1.
[2024/05/21|10:34:56][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|10:35:02][ERROR]:Ignoring exception in command 'disconnect'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 122, in dsiconnect_channel
    await self.music_console.shutdown()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 133, in shutdown
    self.discord_voice_channel.stop()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'disconnect' raised an exception: AttributeError: 'NoneType' object has no attribute 'stop'
[2024/05/21|10:36:48][INFO]:擴充指令初始化完成
[2024/05/21|10:36:48][INFO]:logging in using static token
[2024/05/21|10:36:50][INFO]:Shard ID None has connected to Gateway (Session ID: f4791db26d35418d2f9a5307b253592a).
[2024/05/21|10:36:52][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|10:36:52][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|10:37:02][ERROR]:Ignoring exception in command 'disconnect'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 122, in dsiconnect_channel
    await self.music_console.shutdown()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 134, in shutdown
    self.discord_voice_channel.stop()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'disconnect' raised an exception: AttributeError: 'NoneType' object has no attribute 'stop'
[2024/05/21|10:38:14][INFO]:擴充指令初始化完成
[2024/05/21|10:38:14][INFO]:logging in using static token
[2024/05/21|10:38:15][INFO]:Shard ID None has connected to Gateway (Session ID: 468a7322d0ab890c4678d356d6a52dbc).
[2024/05/21|10:38:18][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|10:38:18][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|10:42:03][INFO]:Connecting to voice...
[2024/05/21|10:42:03][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|10:42:04][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|10:42:17][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 指令處理中
[2024/05/21|10:42:22][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 正在播放あたらよ-「僕は...」(Music Video)/TVアニメ「僕の心のヤバイやつ」第2期OPテーマ
[2024/05/21|10:42:43][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 已暫停當前音樂
[2024/05/21|10:42:48][INFO]:光隱測試區<1029978425550704640> -> test<1146358218696691764> 中的訊息被刪除: 已恢復音樂撥放
[2024/05/21|10:43:00][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|10:43:00][INFO]:ffmpeg process 5736 has not terminated. Waiting to terminate...
[2024/05/21|10:43:00][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|10:43:00][INFO]:ffmpeg process 5736 should have terminated with a return code of 1.
[2024/05/21|14:43:08][INFO]:擴充指令初始化完成
[2024/05/21|14:43:08][INFO]:logging in using static token
[2024/05/21|14:43:09][INFO]:Shard ID None has connected to Gateway (Session ID: 9fcaa79a8337317225de12adb888e066).
[2024/05/21|14:43:12][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|14:43:12][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|14:43:48][INFO]:Connecting to voice...
[2024/05/21|14:43:48][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|14:43:49][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|14:43:54][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 71, in play_music
    await self.music_console.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 231, in start
    self.msg = await self.music.discord_interaction.channel.send(embed=embed,view=view)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji
[2024/05/21|14:44:36][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|14:51:48][INFO]:擴充指令初始化完成
[2024/05/21|14:51:48][INFO]:logging in using static token
[2024/05/21|14:51:49][INFO]:Shard ID None has connected to Gateway (Session ID: 07e417a7f722448203e5ac20a21de516).
[2024/05/21|14:51:52][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|14:51:52][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|14:52:03][INFO]:Connecting to voice...
[2024/05/21|14:52:03][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|14:52:03][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|14:52:07][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 71, in play_music
    await self.music_console.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 232, in start
    self.msg = await self.music.discord_interaction.channel.send(embed=embed,view=view)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji
[2024/05/21|14:52:19][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|14:52:19][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:07:13][INFO]:擴充指令初始化完成
[2024/05/21|15:07:13][INFO]:logging in using static token
[2024/05/21|15:07:14][INFO]:Shard ID None has connected to Gateway (Session ID: eec50055ca5675a657ccec7004314c20).
[2024/05/21|15:07:17][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:07:17][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:07:53][INFO]:Connecting to voice...
[2024/05/21|15:07:53][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:07:53][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:07:57][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 71, in play_music
    await self.music_console.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 232, in start
    self.msg = await self.music.discord_interaction.channel.send(embed=embed,view=view)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji
[2024/05/21|15:09:10][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:09:10][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:10:34][INFO]:擴充指令初始化完成
[2024/05/21|15:10:34][INFO]:logging in using static token
[2024/05/21|15:10:36][INFO]:Shard ID None has connected to Gateway (Session ID: a64cd5840885854e7144218f341fcab8).
[2024/05/21|15:10:38][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:10:38][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:13:31][INFO]:擴充指令初始化完成
[2024/05/21|15:13:31][INFO]:logging in using static token
[2024/05/21|15:13:32][INFO]:Shard ID None has connected to Gateway (Session ID: 3a4d90ba0b0a98392445deb96c0b32a9).
[2024/05/21|15:13:35][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:13:35][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:13:56][INFO]:Connecting to voice...
[2024/05/21|15:13:56][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:13:57][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:14:02][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 71, in play_music
    await self.music_console.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 232, in start
    self.msg = await self.music.discord_interaction.channel.send(embed=embed,view=view)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji
[2024/05/21|15:14:25][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:16:51][INFO]:擴充指令初始化完成
[2024/05/21|15:16:51][INFO]:logging in using static token
[2024/05/21|15:16:52][INFO]:Shard ID None has connected to Gateway (Session ID: 7b022bcc7019638871e11219838f6659).
[2024/05/21|15:16:55][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:16:55][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:17:13][INFO]:Connecting to voice...
[2024/05/21|15:17:13][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:17:13][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:19:46][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:19:46][INFO]:ffmpeg process 8616 has not terminated. Waiting to terminate...
[2024/05/21|15:19:46][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:19:46][INFO]:ffmpeg process 8616 should have terminated with a return code of 1.
[2024/05/21|15:20:40][INFO]:擴充指令初始化完成
[2024/05/21|15:20:40][INFO]:logging in using static token
[2024/05/21|15:20:41][INFO]:Shard ID None has connected to Gateway (Session ID: 0422f5504cbe98237e6d063cd5f94614).
[2024/05/21|15:20:44][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:20:44][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:21:32][INFO]:擴充指令初始化完成
[2024/05/21|15:21:32][INFO]:logging in using static token
[2024/05/21|15:21:34][INFO]:Shard ID None has connected to Gateway (Session ID: 82ce64726faa11a17b60cf644e6926bf).
[2024/05/21|15:21:37][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:21:37][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:22:00][INFO]:Connecting to voice...
[2024/05/21|15:22:00][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:22:00][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:25:58][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:25:58][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:25:58][INFO]:ffmpeg process 2960 has not terminated. Waiting to terminate...
[2024/05/21|15:25:58][INFO]:ffmpeg process 2960 should have terminated with a return code of 1.
[2024/05/21|15:27:26][INFO]:擴充指令初始化完成
[2024/05/21|15:27:26][INFO]:logging in using static token
[2024/05/21|15:27:27][INFO]:Shard ID None has connected to Gateway (Session ID: d49440f40d0dbe8fe94da876ec3b92cc).
[2024/05/21|15:27:30][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:27:30][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:27:50][INFO]:Connecting to voice...
[2024/05/21|15:27:50][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:27:50][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:27:55][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 71, in play_music
    await self.music_console.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 232, in start
    self.msg = await self.music.discord_interaction.channel.send(embed=embed,view=view)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.emoji.name: Invalid emoji
In components.0.components.1.emoji.name: Invalid emoji
In components.0.components.2.emoji.name: Invalid emoji
In components.0.components.3.emoji.name: Invalid emoji
[2024/05/21|15:31:51][INFO]:lightinvi<428845649279188992>在[光隱測試區->test]說:\track_next
[2024/05/21|15:31:55][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:35:23][INFO]:擴充指令初始化完成
[2024/05/21|15:35:23][INFO]:logging in using static token
[2024/05/21|15:35:24][INFO]:Shard ID None has connected to Gateway (Session ID: 79bffef28412eb63861af669efe90499).
[2024/05/21|15:35:27][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:35:27][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:35:40][INFO]:Connecting to voice...
[2024/05/21|15:35:40][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:35:41][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:36:00][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:36:00][INFO]:ffmpeg process 7832 has not terminated. Waiting to terminate...
[2024/05/21|15:36:00][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:36:00][INFO]:ffmpeg process 7832 should have terminated with a return code of 1.
[2024/05/21|15:37:13][INFO]:擴充指令初始化完成
[2024/05/21|15:37:13][INFO]:logging in using static token
[2024/05/21|15:37:15][INFO]:Shard ID None has connected to Gateway (Session ID: 5069702d60108ac19c6263fdc7f384f0).
[2024/05/21|15:37:17][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:37:17][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:37:27][INFO]:Connecting to voice...
[2024/05/21|15:37:27][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:37:27][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:39:01][INFO]:lightinvi<428845649279188992>在[光隱測試區->study]說:🎵
[2024/05/21|15:39:24][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:39:24][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:39:24][INFO]:ffmpeg process 9688 has not terminated. Waiting to terminate...
[2024/05/21|15:39:24][INFO]:ffmpeg process 9688 should have terminated with a return code of 1.
[2024/05/21|15:41:25][INFO]:擴充指令初始化完成
[2024/05/21|15:41:25][INFO]:logging in using static token
[2024/05/21|15:41:26][INFO]:Shard ID None has connected to Gateway (Session ID: 20d3c3779af9fd3a4d3ffb34861af661).
[2024/05/21|15:41:29][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:41:29][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:41:53][INFO]:Connecting to voice...
[2024/05/21|15:41:53][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:41:53][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:42:12][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:42:12][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:42:12][INFO]:ffmpeg process 8088 has not terminated. Waiting to terminate...
[2024/05/21|15:42:12][INFO]:ffmpeg process 8088 should have terminated with a return code of 1.
[2024/05/21|15:44:57][INFO]:擴充指令初始化完成
[2024/05/21|15:44:57][INFO]:logging in using static token
[2024/05/21|15:44:59][INFO]:Shard ID None has connected to Gateway (Session ID: 90adc5d93f66e823b9c17c35c1eb3867).
[2024/05/21|15:45:01][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:45:01][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:45:16][INFO]:Connecting to voice...
[2024/05/21|15:45:16][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:45:17][INFO]:Voice handshake complete. Endpoint found hongkong11099.discord.media
[2024/05/21|15:46:16][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <QueueButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='🎵' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 192, in callback
    string += "\n".join(self.console)
              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, Music found
[2024/05/21|15:46:56][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <PlayPauseButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏯' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 177, in callback
    await interaction.response.send_message(silent=True)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\webhook\async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
[2024/05/21|15:49:12][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:49:12][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:49:12][INFO]:ffmpeg process 7176 has not terminated. Waiting to terminate...
[2024/05/21|15:49:12][INFO]:ffmpeg process 7176 should have terminated with a return code of 1.
[2024/05/21|15:54:49][INFO]:擴充指令初始化完成
[2024/05/21|15:54:49][INFO]:logging in using static token
[2024/05/21|15:54:51][INFO]:Shard ID None has connected to Gateway (Session ID: 5f0edd0c00beee8c437e56dbe7024943).
[2024/05/21|15:54:53][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:54:53][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:55:00][INFO]:更新 profileOnline 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|15:55:00][INFO]:更新 profileStar 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|15:55:00][INFO]:lightinvi<428845649279188992> 加入 光隱測試區<1029978425550704640> 的語音頻道
[2024/05/21|15:55:06][INFO]:Connecting to voice...
[2024/05/21|15:55:06][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:55:06][INFO]:Voice handshake complete. Endpoint found hongkong6825.discord.media
[2024/05/21|15:56:40][INFO]:ffmpeg process 5404 has not terminated. Waiting to terminate...
[2024/05/21|15:56:40][INFO]:ffmpeg process 5404 should have terminated with a return code of 1.
[2024/05/21|15:56:44][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:56:44][INFO]:ffmpeg process 8912 has not terminated. Waiting to terminate...
[2024/05/21|15:56:45][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:56:45][INFO]:ffmpeg process 8912 should have terminated with a return code of 1.
[2024/05/21|15:58:29][INFO]:擴充指令初始化完成
[2024/05/21|15:58:29][INFO]:logging in using static token
[2024/05/21|15:58:31][INFO]:Shard ID None has connected to Gateway (Session ID: e8ca98638c94af4c98adbb39b76ae242).
[2024/05/21|15:58:34][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|15:58:34][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|15:58:47][INFO]:Connecting to voice...
[2024/05/21|15:58:47][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|15:58:48][INFO]:Voice handshake complete. Endpoint found hongkong6825.discord.media
[2024/05/21|15:59:29][INFO]:ffmpeg process 4556 has not terminated. Waiting to terminate...
[2024/05/21|15:59:29][INFO]:ffmpeg process 4556 should have terminated with a return code of 1.
[2024/05/21|15:59:30][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|15:59:30][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|15:59:32][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <SkipButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏭' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 168, in callback
    await self.console.skip()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 260, in skip
    await self.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 235, in start
    self.discord_voice_channel.play(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\voice_client.py", line 605, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
[2024/05/21|15:59:32][INFO]:ffmpeg process 5024 has not terminated. Waiting to terminate...
[2024/05/21|15:59:32][INFO]:ffmpeg process 5024 should have terminated with a return code of 1.
[2024/05/21|16:07:01][INFO]:擴充指令初始化完成
[2024/05/21|16:07:01][INFO]:logging in using static token
[2024/05/21|16:07:03][INFO]:Shard ID None has connected to Gateway (Session ID: 31dcc3134b64693dacf6776d2e2fa6d0).
[2024/05/21|16:07:05][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|16:07:05][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|16:07:28][INFO]:Connecting to voice...
[2024/05/21|16:07:28][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:07:28][INFO]:Voice handshake complete. Endpoint found hongkong6825.discord.media
[2024/05/21|16:08:28][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:08:28][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|16:09:28][INFO]:擴充指令初始化完成
[2024/05/21|16:09:28][INFO]:logging in using static token
[2024/05/21|16:09:30][INFO]:Shard ID None has connected to Gateway (Session ID: d9fc12f1f5c027e2c149b1c9ca88a2e5).
[2024/05/21|16:09:32][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|16:09:32][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|16:09:48][WARNING]:lightinvi<428845649279188992> 異常上線時間紀錄
[2024/05/21|16:10:56][INFO]:更新 profileOnline 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|16:10:56][INFO]:更新 profileStar 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|16:10:56][INFO]:lightinvi<428845649279188992> 加入 光隱測試區<1029978425550704640> 的語音頻道
[2024/05/21|16:11:15][INFO]:Connecting to voice...
[2024/05/21|16:11:15][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:11:16][INFO]:Voice handshake complete. Endpoint found hongkong11035.discord.media
[2024/05/21|16:11:49][INFO]:ffmpeg process 8132 has not terminated. Waiting to terminate...
[2024/05/21|16:11:49][INFO]:ffmpeg process 8132 should have terminated with a return code of 1.
[2024/05/21|16:11:50][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:11:50][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|16:11:52][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <SkipButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏭' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 168, in callback
    await self.console.skip()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 261, in skip
    await self.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 236, in start
    self.discord_voice_channel.play(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\voice_client.py", line 605, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
[2024/05/21|16:11:52][INFO]:ffmpeg process 4976 has not terminated. Waiting to terminate...
[2024/05/21|16:11:53][INFO]:ffmpeg process 4976 should have terminated with a return code of 1.
[2024/05/21|16:13:31][INFO]:更新 profileOnline 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|16:13:31][INFO]:更新 profileStar 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|16:13:31][INFO]:lightinvi<428845649279188992> 於 光隱測試區<1029978425550704640> 獲得 2貢獻值 和 3碎星值
[2024/05/21|16:18:52][INFO]:擴充指令初始化完成
[2024/05/21|16:18:52][INFO]:logging in using static token
[2024/05/21|16:18:54][INFO]:Shard ID None has connected to Gateway (Session ID: 4f3afb7a468dec68f81dc8618fc7f38d).
[2024/05/21|16:18:58][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|16:18:58][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|16:19:12][INFO]:更新 profileOnline 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|16:19:12][INFO]:更新 profileStar 成功->UUID: D6FAAA3F-D601-458C-B1F6-9AB11E929F54
[2024/05/21|16:19:12][INFO]:lightinvi<428845649279188992> 加入 光隱測試區<1029978425550704640> 的語音頻道
[2024/05/21|16:19:15][INFO]:Connecting to voice...
[2024/05/21|16:19:15][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:19:16][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|16:19:47][INFO]:ffmpeg process 4936 has not terminated. Waiting to terminate...
[2024/05/21|16:19:47][INFO]:ffmpeg process 4936 should have terminated with a return code of 1.
[2024/05/21|16:19:48][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <SkipButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏭' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 168, in callback
    await self.console.skip()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 262, in skip
    await self.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 233, in start
    await self.msg.edit(embed=embed,view=view)
                                         ^^^^
UnboundLocalError: cannot access local variable 'view' where it is not associated with a value
[2024/05/21|16:19:48][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:19:48][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|16:21:25][INFO]:擴充指令初始化完成
[2024/05/21|16:21:25][INFO]:logging in using static token
[2024/05/21|16:21:27][INFO]:Shard ID None has connected to Gateway (Session ID: 07be3027cb05ccb297e91d18bf582dc8).
[2024/05/21|16:21:29][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|16:21:29][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|16:21:40][INFO]:Connecting to voice...
[2024/05/21|16:21:40][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:21:40][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|16:21:57][INFO]:ffmpeg process 6488 has not terminated. Waiting to terminate...
[2024/05/21|16:21:57][INFO]:ffmpeg process 6488 should have terminated with a return code of 1.
[2024/05/21|16:21:58][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:22:02][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <SkipButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏭' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 168, in callback
    await self.console.skip()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 262, in skip
    await self.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 237, in start
    self.discord_voice_channel.play(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\voice_client.py", line 605, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
[2024/05/21|16:22:02][INFO]:ffmpeg process 2728 has not terminated. Waiting to terminate...
[2024/05/21|16:22:02][INFO]:ffmpeg process 2728 should have terminated with a return code of 1.
[2024/05/21|16:22:02][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|16:23:04][INFO]:Connecting to voice...
[2024/05/21|16:23:04][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:23:05][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|16:23:58][INFO]:ffmpeg process 4232 has not terminated. Waiting to terminate...
[2024/05/21|16:23:58][INFO]:ffmpeg process 4232 should have terminated with a return code of 1.
[2024/05/21|16:23:59][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:23:59][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|16:24:01][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <SkipButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏭' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 168, in callback
    await self.console.skip()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 262, in skip
    await self.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 237, in start
    self.discord_voice_channel.play(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\voice_client.py", line 605, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
[2024/05/21|16:24:01][INFO]:ffmpeg process 928 has not terminated. Waiting to terminate...
[2024/05/21|16:24:02][INFO]:ffmpeg process 928 should have terminated with a return code of 1.
[2024/05/21|16:31:12][INFO]:擴充指令初始化完成
[2024/05/21|16:31:12][INFO]:logging in using static token
[2024/05/21|16:31:14][INFO]:Shard ID None has connected to Gateway (Session ID: 39428e7be24e4114c9f3dfe309d1a4b2).
[2024/05/21|16:31:16][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|16:31:16][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|16:31:39][INFO]:Connecting to voice...
[2024/05/21|16:31:39][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:31:39][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|16:31:56][INFO]:ffmpeg process 10600 has not terminated. Waiting to terminate...
[2024/05/21|16:31:56][INFO]:ffmpeg process 10600 should have terminated with a return code of 1.
[2024/05/21|16:31:57][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:31:59][ERROR]:Ignoring exception in view <View timeout=180.0 children=4> for item <SkipButton style=<ButtonStyle.secondary: 2> url=None disabled=False label=None emoji=<PartialEmoji animated=False name='⏭' id=None> row=None>
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 169, in callback
    await self.console.skip()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 265, in skip
    await self.start()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 240, in start
    self.discord_voice_channel.play(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\voice_client.py", line 605, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.
[2024/05/21|16:31:59][INFO]:ffmpeg process 6304 has not terminated. Waiting to terminate...
[2024/05/21|16:31:59][INFO]:ffmpeg process 6304 should have terminated with a return code of 1.
[2024/05/21|16:31:59][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|16:35:27][INFO]:Connecting to voice...
[2024/05/21|16:35:27][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:35:27][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|16:35:41][INFO]:ffmpeg process 2020 has not terminated. Waiting to terminate...
[2024/05/21|16:35:41][INFO]:ffmpeg process 2020 should have terminated with a return code of 1.
[2024/05/21|16:35:41][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:35:42][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|16:35:44][ERROR]:Ignoring exception in command 'skip'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 84, in skip_music
    await self.music_console.skip()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 265, in skip
    """暫停音樂"""
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 240, in start
    source=F"storge\\system\\music\\{self.music.id}.mp4"
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\voice_client.py", line 605, in play
    raise ClientException('Not connected to voice.')
discord.errors.ClientException: Not connected to voice.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'skip' raised an exception: ClientException: Not connected to voice.
[2024/05/21|16:35:44][INFO]:ffmpeg process 3304 has not terminated. Waiting to terminate...
[2024/05/21|16:35:44][INFO]:ffmpeg process 3304 should have terminated with a return code of 1.
[2024/05/21|16:42:19][INFO]:擴充指令初始化完成
[2024/05/21|16:42:19][INFO]:logging in using static token
[2024/05/21|16:42:20][INFO]:Shard ID None has connected to Gateway (Session ID: 81f1e6c55a5476fc0e1b69acb1264f1c).
[2024/05/21|16:42:23][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|16:42:23][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|16:42:37][INFO]:Connecting to voice...
[2024/05/21|16:42:37][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|16:42:37][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|16:42:59][INFO]:ffmpeg process 10540 has not terminated. Waiting to terminate...
[2024/05/21|16:42:59][INFO]:ffmpeg process 10540 should have terminated with a return code of 1.
[2024/05/21|16:45:36][INFO]:ffmpeg process 7212 successfully terminated with return code of 0.
[2024/05/21|16:45:36][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|16:45:36][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|17:03:51][INFO]:擴充指令初始化完成
[2024/05/21|17:03:51][INFO]:logging in using static token
[2024/05/21|17:03:53][INFO]:Shard ID None has connected to Gateway (Session ID: 98d1369b2a0badca4812bf546f6d45bd).
[2024/05/21|17:03:56][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|17:03:56][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|17:04:34][INFO]:lightinvi<428845649279188992>在[光隱測試區->study]說:https://youtu.be/go6cEYPA5RI?si=IpRyJllRyTCbHM3U
[2024/05/21|17:04:34][INFO]:光隱測試區<1029978425550704640> -> study<1163727016554659910> 中的訊息被編輯: https://youtu.be/go6cEYPA5RI?si=IpRyJllRyTCbHM3U -> https://youtu.be/go6cEYPA5RI?si=IpRyJllRyTCbHM3U
[2024/05/21|17:05:29][INFO]:Connecting to voice...
[2024/05/21|17:05:29][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:05:29][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:05:33][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 56, in play_music
    music = F"https://www.youtube.com{music[0]['url_suffix']}"
                                      ~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: IndexError: list index out of range
[2024/05/21|17:07:06][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:09:01][INFO]:擴充指令初始化完成
[2024/05/21|17:09:01][INFO]:logging in using static token
[2024/05/21|17:09:02][INFO]:Shard ID None has connected to Gateway (Session ID: 37d537bd8881e6983ace1ebdea4cf196).
[2024/05/21|17:09:05][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|17:09:05][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|17:09:30][INFO]:Connecting to voice...
[2024/05/21|17:09:30][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:09:31][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:09:32][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:09:32][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|17:30:17][INFO]:擴充指令初始化完成
[2024/05/21|17:30:17][INFO]:logging in using static token
[2024/05/21|17:30:19][INFO]:Shard ID None has connected to Gateway (Session ID: ac9d498cb93621bcd2feeccdb40121a5).
[2024/05/21|17:30:21][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|17:30:21][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|17:30:37][INFO]:Connecting to voice...
[2024/05/21|17:30:37][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:30:38][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:30:40][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:30:40][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|17:33:23][INFO]:擴充指令初始化完成
[2024/05/21|17:33:23][INFO]:logging in using static token
[2024/05/21|17:33:25][INFO]:Shard ID None has connected to Gateway (Session ID: 6186f26301dc701369f1f026940e85a7).
[2024/05/21|17:33:27][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|17:33:27][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|17:33:41][INFO]:Connecting to voice...
[2024/05/21|17:33:41][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:33:41][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:33:42][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:33:42][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|17:44:27][INFO]:擴充指令初始化完成
[2024/05/21|17:44:27][INFO]:logging in using static token
[2024/05/21|17:44:28][INFO]:Shard ID None has connected to Gateway (Session ID: fcc7ae4e1ea69928e91abc1710c5d2d5).
[2024/05/21|17:44:32][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|17:44:32][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|17:44:51][INFO]:Connecting to voice...
[2024/05/21|17:44:51][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:44:52][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:44:53][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:44:53][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|17:45:47][INFO]:Connecting to voice...
[2024/05/21|17:45:47][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:45:47][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:49:22][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:49:22][INFO]:ffmpeg process 8088 has not terminated. Waiting to terminate...
[2024/05/21|17:49:22][INFO]:ffmpeg process 8088 should have terminated with a return code of 1.
[2024/05/21|17:51:14][INFO]:擴充指令初始化完成
[2024/05/21|17:51:14][INFO]:logging in using static token
[2024/05/21|17:51:16][INFO]:Shard ID None has connected to Gateway (Session ID: c2e4ad507bdc2b2e1c967aee7bfc6198).
[2024/05/21|17:51:18][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|17:51:18][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|17:51:48][INFO]:Connecting to voice...
[2024/05/21|17:51:48][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:51:48][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:51:50][ERROR]:Ignoring exception in command 'music'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 38, in play_music
    await interactions.response.send_message("",delete_after=1)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\interactions.py", line 801, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\webhook\async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'music' raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
[2024/05/21|17:52:25][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:53:04][INFO]:擴充指令初始化完成
[2024/05/21|17:53:04][INFO]:logging in using static token
[2024/05/21|17:53:05][INFO]:Shard ID None has connected to Gateway (Session ID: 10f83540e5d87400f9df59121387b82b).
[2024/05/21|17:53:08][INFO]:已載入21個斜線指令
['樂透<1242290397108240507>', 'lottery<1242290397108240508>', '伺服器<1242290397108240509>', '開啟伺服器<1242290397108240510>', '關閉伺服器<1242290397108240511>', '重啟伺服器<1242290397108240513>', 'music<1242290397108240514>', 'skip<1242290397108240515>', 'pause<1242303741445668884>', 'resume<1242303741445668885>', 'disconnect<1242303741445668886>', '我<1242290397108240516>', '其他人<1242290397221228594>', '排行<1242290397221228595>', 'me<1242290397221228596>', 'other<1242290397221228597>', 'ranking<1242290397221228598>', '獲取驗證碼<1242290397221228599>', '驗證<1242290397221228600>', 'get_verification<1242290397221228602>', 'verify<1242290397221228603>']
[2024/05/21|17:53:08][INFO]: >>夕由愛XitoAi已成功連線Discord<< 
[2024/05/21|17:53:37][INFO]:Connecting to voice...
[2024/05/21|17:53:37][INFO]:Starting voice handshake... (connection attempt 1)
[2024/05/21|17:53:38][INFO]:Voice handshake complete. Endpoint found hongkong11051.discord.media
[2024/05/21|17:54:09][INFO]:Disconnecting from voice normally, close code 1000.
[2024/05/21|17:54:09][INFO]:ffmpeg process 8912 has not terminated. Waiting to terminate...
[2024/05/21|17:54:09][INFO]:ffmpeg process 8912 should have terminated with a return code of 1.
[2024/05/21|17:54:09][INFO]:The voice handshake is being terminated for Channel ID 1029978426192433165 (Guild ID 1029978425550704640)
[2024/05/21|17:54:09][ERROR]:Ignoring exception in command 'disconnect'
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\test\Desktop\Discord_XitoAi\src\commands\music.py", line 126, in dsiconnect_channel
    await self.music_console.shutdown()
  File "c:\Users\test\Desktop\Discord_XitoAi\src\methods\OAM_music.py", line 253, in shutdown
    await self.msg.delete()
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\message.py", line 859, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\http.py", line 741, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Roaming\Python\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'disconnect' raised an exception: NotFound: 404 Not Found (error code: 10008): Unknown Message
